spring:
  profiles.include: api
  datasource:
    url: jdbc:postgresql://localhost:5432/shary
    username: shary
    password: 1234567890
server.port: 8090

spring.jpa:
  # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
  properties.hibernate.temp.use_jdbc_metadata_defaults: false
  # Because detection is disabled you have to set correct dialect by hand.
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  # Hibernate ddl auto (create, create-drop, validate, update)
  hibernate.ddl-auto: create


